baseURL = "https://FierceX.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "FierceX's Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "even"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 15                                              # （可选）首页显示的文章条目数量，默认为10
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

[author]                  # require                       # 必需
  name = "FierceX"

[sitemap]                 # require                       # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"

[params]
  since = "2017"            # Site creation time          # 站点建立时间

  # site info (option)                                    # 站点信息（可选）
  logoTitle = "FierceX's Blog"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","even"]
  description = "Hugo theme even example site."

  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目
  archive-paginate = 15
  
  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = false

  # 一些全局开关，你可以在每一篇内容的 front matter 中单独关闭某些选项
  # Some global options, you can close something in front matter.
  toc = true                                                                            # 是否开启目录
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = true            # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. # 是否在链接到markdown原始文件（如果你配置了下面的许可协议并允许hugo生成markdown文件）

  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.social]                                         # 社交链接
    a-email = "mailto:FierceX@outlook.com"
    #e-linkedin = "https://github.com/FierceX"
    g-github = "https://github.com/FierceX"
    #h-weibo = "http://localhost:1313"

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffix = "md"
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
