baseurl = "https://FierceX.github.io/"
title = "FierceX"
theme = "ghostwriter"
languageCode = "zh-cn"
copyright = "FierceX"

[Author]
    name = "FierceX"
    profile = "https://FierceX.github.io"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "夏鲁豫"
    description = "路漫漫其修远兮，吾将上下而求索"
    github = "https://github.com/fiercex"
    #linkedin = "https://linkedin.com/in/XXX/"
    #gplus = "https://google.com/+XXX"
    #twitter = "https://twitter.com/XXX"
    #stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "mailto:FierceX@outlook.com"
    opengraph = true
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    #dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    #post = "/:year/:month/:day/:filename/"
    post = "/post/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

#[[menu.main]]
#    name = "Projects"
#    url = "/project/"
#    weight = 2

#[[menu.main]]
#    name = "Contact"
#    url = "/page/contact/"
#    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
